from .models.JerarquiaAcad import JerarquiaAcad
from .models.Institucion import Institucion
from .models.Facultad import Facultad
from .models.Escuela import Escuela
from .models.Carrera import Carrera
from .models.NaturalPerson import NaturalPerson
from skyend_configs.models.UnidadMedida import UnidadMedida
from .models.Insumo import Insumo
from .models.Categoria import Categoria
